_wandb:
    value:
        cli_version: 0.19.9
        m:
            - "1": field_reconstruction.format
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": field_reconstruction.width
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": field_reconstruction.height
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": field_reconstruction._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": field_reconstruction.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": field_reconstruction.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": field_reconstruction.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
                - 103
                - 106
            "2":
                - 1
                - 9
                - 41
                - 55
                - 103
                - 106
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
accumulate_gradients:
    value: null
batch_size:
    value: 8
camels_data:
    value: LH
camels_suite:
    value: Astrid
eval_every:
    value: 50
gpus:
    value: 6
grad_clip:
    value: 1
latent_dim:
    value: 256
latent_img_channels:
    value: 8
learning_rate:
    value: 5e-05
log_wandb:
    value: true
max_epochs:
    value: 100
max_steps:
    value: 2000
num_workers:
    value: 4
output_dir:
    value: ""
profile:
    value: false
reverse:
    value: false
root:
    value: /monolith/global_data/astro_compression/CAMELS
run_name:
    value: final_test
save_every:
    value: 50
train_size:
    value: 14000
unconditional:
    value: false
use_wandb:
    value: true
val_size:
    value: 1000
